name: personal_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  flutter_local_notifications: ^18.0.1
  firebase_storage: ^12.3.7
  curved_navigation_bar: ^1.0.6
  google_nav_bar: ^5.0.7
  firebase_messaging: ^15.1.6
  app_settings: ^5.1.1
  image_picker: ^1.1.2
  fl_chart: ^0.69.2
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logopng.png   # Include the correct path to your logo file
    - assets/onlylogo.png  # Include another asset if needed
fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Pop.ttf
      - asset: fonts/PopB.ttf
        weight: 700